name: Trigger auto deployment for foodpro

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/foodpro-AutoDeployTrigger-5f78b984-4877-4397-9485-1c28b9ecb867.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FOODPRO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FOODPRO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FOODPRO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend/RecipeMeal
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: foodpro.azurecr.io
          registryUsername: ${{ secrets.FOODPRO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FOODPRO_REGISTRY_PASSWORD }}
          containerAppName: foodpro
          resourceGroup: recipemeal
          imageToBuild: foodpro.azurecr.io/foodpro:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


